Task 4 Nodemon
Himanshu0k/StudyIn-himanshuKumar pull request #4
Opened 2024-10-01 13:44 UTC by Himanshu0k

2024-10-02 07:35 UTC, GargPermil commented on package.json
> +    "nodemon": "^3.1.7"
need configuration as well.

2024-10-02 13:13 UTC, Himanshu0k commented on package.json
> +    "nodemon": "^3.1.7"
added.

2024-10-05 09:24 UTC, GargPermil requested changes
remove node modules.

2024-10-06 06:48 UTC, Himanshu0k commented
removed.

2024-10-06 11:32 UTC, merged